### ISSUE TITLE
Console Exception Spam > PlayerMoveEvent v1.0.0.10

### ISSUE THREAD

**Issue by vlcik128** [BlockAuraDevs/AdminSecurity#11]
[15:03:44 ERROR]: Could not pass event PlayerMoveEvent to BAAdminSec v1.0.0.10
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Bukkit-e91aed8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-Bukkit-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:256) [server.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [server.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [server.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Bukkit-e91aed8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [server.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:676) [server.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [server.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [server.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [server.jar:git-Bukkit-e91aed8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
        at **dev.BlockAura.AdminSecurity.handlers.AuthSec.onMove(AuthSec.java:51)** ~[?:?]
        at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-Bukkit-e91aed8]
        ... 15 more

**Comment by vlcik128** [comment]
Pokus o opravu

**Comment by vlcik128** [comment]
CHYBA NIE JE OPRAVITEĽNÁ! 
Nesmiete používať /reload!
